server {

 listen 80;
	
        error_log /opt/homebrew/var/log/nginx/model-runner.error.log;
        access_log /opt/homebrew/var/log/nginx/model-runner.access.log;
        set $root  "/Users/jzx/Documents/work-station/model-runner/client/bundle";
        set $serverApi "http://127.0.0.1:3000";
    location / {
        root  $root;
        index index.html;
	try_files $uri $uri/ /index.html;
       # proxy_pass                  http://127.0.0.1:8080;
    }
    location /model/ {
        proxy_pass                          $serverApi;
    }
    location /pay/ {
        proxy_pass                          $serverApi;
    }
    location /user/ {
        proxy_pass                          $serverApi;
    }
}